version: '3.7'
services:
  app: 
    container_name: test_task_app
    build: ./
    depends_on:
      - db
    volumes:
      - ./src:/fastapi_app/src
    ports:
      - 9999:8000
    restart: always
    env_file:
      - src/.env


  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - .postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex09
      - POSTGRES_DB=test_task
    env_file:
      - src/.env
    ports:
      - 5432:5432
    restart: always

